// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTbo6R4YNKT8KgCJkMUPlxJ2us7H5_xU',
    appId: '1:722908583435:web:d15a29f06e442d041f590e',
    messagingSenderId: '722908583435',
    projectId: 'unicvtrab',
    authDomain: 'unicvtrab.firebaseapp.com',
    storageBucket: 'unicvtrab.appspot.com',
    measurementId: 'G-TMY2G43QZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVbM-oW32q_W86zZ8LQh9Vr0REhYncJw',
    appId: '1:722908583435:android:45d77119d6953d251f590e',
    messagingSenderId: '722908583435',
    projectId: 'unicvtrab',
    storageBucket: 'unicvtrab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9AGqNzMK47-JD7zy4LBgHFFnAO36G70',
    appId: '1:722908583435:ios:60b2e6e0c8b0bfe31f590e',
    messagingSenderId: '722908583435',
    projectId: 'unicvtrab',
    storageBucket: 'unicvtrab.appspot.com',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9AGqNzMK47-JD7zy4LBgHFFnAO36G70',
    appId: '1:722908583435:ios:60b2e6e0c8b0bfe31f590e',
    messagingSenderId: '722908583435',
    projectId: 'unicvtrab',
    storageBucket: 'unicvtrab.appspot.com',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdTbo6R4YNKT8KgCJkMUPlxJ2us7H5_xU',
    appId: '1:722908583435:web:ab1c173b7b7dc7431f590e',
    messagingSenderId: '722908583435',
    projectId: 'unicvtrab',
    authDomain: 'unicvtrab.firebaseapp.com',
    storageBucket: 'unicvtrab.appspot.com',
    measurementId: 'G-3JLBE9Z7LP',
  );

}